### ISSUE TITLE
moblog_lang.php requires unexistant file

### ISSUE THREAD

**Issue by nibelune** [EllisLab/EE-Language-French#10]
moblog_lang.php requires ee/EllisLab/Addons/moblog/language/french/moblog_lang.php. the file doesn't exist. It would be nice to include it... or to keep the path to the english version.

**Comment by ebeauchamps** [comment]
Sure, you are right. I discussed with Wes Baker today and he is OK that I put back the full French moblog_lang.php file in this repo.

**Comment by ebeauchamps** [comment]
Solved

**Comment by wesbaker** [comment]
Added in #11
